### ISSUE TITLE
Can I suppress errors?

### ISSUE THREAD

**Issue by dcplebranch** [a-digital/eventbrite#11]
When accessing an invalid event ID, I get the following error printed on the front end:

Error 404 retrieving data from Eventbrite: The event you requested does not exist.

However, I would like to suppress this error on the front end so that my users do not see this. If there is an error, the event variable should contain that error message and I can handle it on my end, correct?

Let me know if this is possible please. Thanks,

**Comment by mark-adigital** [comment]
Hi @dcplebranch  - sorry for the late reply here. I'm taking some annual leave next week, but I have just committed a conditional around that print statement so it's only output on dev and staging environments, but not live. The best conditional to add on the frontend is this:

```
{% set events = craft.eventbrite.allEvents() %}
{% if events|length > 0 %}
  // For loop, show events
{% else %}
  // Show message saying no events found
{% endif %}
```

**Comment by dcplebranch** [comment]
Hey, this kinda works, but I'm running into another problem, maybe related?

One of my outside ids is creating an error: “Error 403 retrieving data from Eventbrite: You do not have permission to access the resource you requested.”

On my local VM, it gives this error when I run the allEvents() method, but then still shows all the other events.

However, on the production machine, the page doesn't load at all and it says "Internal Server Error"

It's a simple fix, just remove the invalid ID... however, it would be nice for it to not totally fail when an ID causes an error, and to just kinda skip over it quietly maybe?

**Comment by mark-adigital** [comment]
As I just mentioned over in #13 , I never released that change to suppress the errors so I'll do that now and that may resolve your problem on production. Just a tip, you can also go into your user settings on newer versions of Craft so you can see Twig error output when logged in as an admin user in production (screenshot attached).

<img width="1126" alt="Screenshot 2022-09-20 at 12 24 39" src="https://user-images.githubusercontent.com/30312669/191245569-e0abea4d-df7d-4071-9f83-a0b09e983856.png">
